# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_remove_quote_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='quotes',
        ),
    ]
