# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 17:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0003_auto_20170224_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='favorites',
        ),
    ]
