# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_remove_quote_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='stars',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='Post.User'),
            preserve_default=False,
        ),
    ]
